# Numpy

Numpy basically provides a high-performance multidimensional array object and tools for working with these arrays.

### Arrays

We can initialize numpy arrays from nested Python lists, and access elements using square brackets

In [70]:
import numpy as np

In [71]:
a = np.array([1, 2, 3])  # create a rank 1 array
print(type(a))

<class 'numpy.ndarray'>


the shape of the array refers in a mathematical sense to the size of the matrix

the rank or the dimension of the array is the number of scalar indices you need to obtain a scalar value

the axis of the array is roughly synonymous with dimension

In [72]:
print(a.shape)
print(a.ndim)  # the rank of the array
print(a.size)  # number of elements in the array

(3,)
1
3


you can also index into the array

In [73]:
a[0] = 5
print(a)

[5 2 3]


In [74]:
b = np.array([[1, 2, 3], [4, 5, 6]])  # create a rank 2 array
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


numpy also provides many functions to create arrays

In [75]:
a = np.zeros((2,2))  # create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [76]:
b = np.ones((1,2))  # create a 1x2 array of all ones
print(b)

[[1. 1.]]


In [77]:
c = np.full((2,2), 7) # create a 2x2 array that contains 7 at all indexes
print(c)

[[7 7]
 [7 7]]


In [78]:
d = np.eye(3)  # create a 3x3 identity matrix
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [79]:
e = np.random.random((3,3))  # create a random 3x3 array
print(e)

[[0.3646697  0.73566938 0.44179845]
 [0.0042344  0.53871023 0.06839354]
 [0.66195538 0.82333291 0.38212124]]


## Array indexing

There are several ways to index into arrays:

### slicing

In [80]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])  # create a 3x4 array

# use slicing to pull out the subarray consisting
# of the first 2 rows and columns 1 and 2
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [81]:
# a slice of an array is a view into the same data, so
# modifying it will modify the original array
print(a[0, 1])
b[0, 0] = 77  # b[0, 0] is the same as a[0, 1]
print(a[0, 1])

2
77


mixing integer indexing with slices yields an array of lower rank, ie.

In [82]:
row_r1 = a[1, :]  # integer indexing is mixed with slices
print(row_r1)
print(row_r1.ndim)

[5 6 7 8]
1


but using only slices yields an array of the same rank as the original array, ie.

In [83]:
row_r2 = a[1:2, :]  # indexing uses only slices
print(row_r2)
print(row_r2.ndim)
print(row_r2.shape)

[[5 6 7 8]]
2
(1, 4)


we can also do column indexing

In [84]:
col_c1 = a[:, 2:3]  # indexing uses only slices
print(col_c1)

[[ 3]
 [ 7]
 [11]]


one useful trick with integer array indexing is selecting or mutating one element from each row of a matrix

In [85]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

# create an array of indices
b = np.array([0, 2, 0, 1])

# select one element from each row of 'a' using the indices in b
print(a[np.arange(4), b])

# mutate one element from each row of 'a' using the indices in b
a[np.arange(4), b] += 10

print(a)

[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


### Boolean array indexing

used to select the elements of an array that satisfy some condition

In [86]:
a = np.array([[1,2], [3,4], [5,6]])

bool_idx = (a > 2)  # find the elements of 'a' that are greater than 2
                    # this returns a numpy array of booleans of the  same shape shape as a

print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [87]:
# use boolean array indexing to construct rank 1 array
# that contain the elements for which the condition was true

print(a[bool_idx])

# we can do all of the above in a single consice statement
print(a[a > 2])


[3 4 5 6]
[3 4 5 6]


## Datatypes

Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype

In [88]:
x = np.array([1.0, 2.0])  # let numpy choose the datatype
print(x.dtype)

x = np.array([1, 2], dtype=np.int64)  # force a particular datatype
print(x.dtype)

float64
int64


## Array math

In [89]:
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[5,6], [7,8]], dtype=np.float64)

# elementwise sum: 2 ways
print(x + y)
print(np.add(x, y))  # both will produce the same results

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [90]:
# elementwise difference
print(x - y)
print(np.subtract(x, y))  # both will produce the same results

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [91]:
# elementwise product
print(x * y)
print(np.multiply(x, y))  # both will produce the same results

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [92]:
# elementwise division
print(x / y)
print(np.divide(x, y))  # both produce the same results

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [93]:
# elementwise square root
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


we use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices

In [94]:
v = np.array([9, 10])
w = np.array([11, 12])

# inner product of vectors; both produce the same results
print(v.dot(w))
print(np.dot(v, w))

219
219


In [95]:
# matrix / vector product; both produce a rank 1 array
print(x.dot(v))
print(np.dot(x, v))

[29. 67.]
[29. 67.]


In [96]:
# matrix / matrix product; both produce a rank 2 array
print(x.dot(y))
print(np.dot(x, y))

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [97]:
# compute sum of all elements in the array
print(np.sum(x))

10.0


In [98]:
# compute sum of each column
print(np.sum(x, axis=0))

# compute sum of each row
print(np.sum(x, axis=1))

[4. 6.]
[3. 7.]


In [99]:
# prints the transpose of the matrix
print(x.T)
# note that taking the transpose of a rank 1 array does nothing

[[1. 3.]
 [2. 4.]]


## Broadcasting

Allows numpy to work with arrays of different shapes when performing arithmetic operations.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [100]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1,0,1])
y = np.empty_like(x)  # create an empty matrix with the same shape as x

vv = np.tile(v, (4, 1))  # stack 4 copies of v on top of each other

y = x + vv
print(y)


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of 'v'.
Consider this version, using broadcasting:

In [101]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1,0,1])

y = x + v  # add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

In order to broadcast, the size of the trailing axes for both arrays in an operation must either be the same size or one of them must be one. eg.

Image  (3d array): 256 x 256 x 3
Scale  (1d array):             3
Result (3d array): 256 x 256 x 3


A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5

A two dimensional array multiplied by a one dimensional array results in broadcasting if number of 1-d array elements matches the number of 2-d array columns.

Applications of broadcasting

In [102]:
# compute outer product of vectors
v = np.array([1,2,3])
w = np.array([4,5])

# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [103]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
